### ISSUE TITLE
External link icon

### ISSUE THREAD

**Issue by rJIynbIuKOT** [ftnext/sphinx-new-tab-link#15]
Hi. Could you add a setting to add icon to an external link? For example, `link-external` from https://sphinx-design.readthedocs.io/en/latest/badges_buttons.html#inline-icons

**Comment by ftnext** [comment]
@rJIynbIuKOT Thank you for sharing your idea.

Does the sphinx-new-tab-link with this feature build the following HTML?
I would like to ask for you to comment on this mock.
<img width="531" alt="image" src="https://github.com/ftnext/sphinx-new-tab-link/assets/21273221/f8e021a2-054f-4379-a653-73a51ecd352b">

**Comment by rJIynbIuKOT** [comment]
@FredM67 Yes, that's exactly what I want.
So that the user immediately understands that the link leads to an external resource.

**Comment by ftnext** [comment]
@rJIynbIuKOT Thanks. I just released [0.5.0](https://pypi.org/project/sphinx-new-tab-link/0.5.0/), please try it.
Documentation is here: https://github.com/ftnext/sphinx-new-tab-link/tree/v0.5.0?tab=readme-ov-file#new_tab_link_show_external_link_icon
