### ISSUE TITLE
show_external_link_icon is not compatible with .. image:: :target:

### ISSUE THREAD

**Issue by ChristianH99** [ftnext/sphinx-new-tab-link#16]
When using new tab link with the new_tab_link_show_external_link_icon option set to true, to link a image to a external site, using the :target: function, the image will not be displayed. Instead the external_link_icon will be displayed. 

Using :target: with an image should not lead to the external_link_icon being displayed.

**Comment by ftnext** [comment]
Thanks for letting me know.

I think I've fixed it. I'll release it later (as 0.5.1).

<img width="983" alt="スクリーンショット 2024-07-29 9 22 47" src="https://github.com/user-attachments/assets/a3a34bfc-8038-4c3f-93df-bd6044875e08">

**Comment by ftnext** [comment]
@ChristianH99 Thanks for bug report. I just released a fixed version [0.5.1](https://pypi.org/project/sphinx-new-tab-link/0.5.1/), which supports `.. image` directive's  `:target:` option.
